name: Update Data

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: pip install requests

      # Run your existing scripts
      - name: Update Data
        run: |
          if [ ! -f "precipitation_data.csv" ]; then
            python backfill_weather.py
          else
            python get_daily_weather.py
          fi
          python get_daily_weather.py

      # Pull latest changes before committing
      - run: git pull --rebase
        name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Daily data update"
          file_pattern: "precipitation_data.csv"
